/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.brasilsistemas.mysystem.view;
import br.com.brasilsistemas.mysystem.model.Usuario;


/**
 *
 * @author joanderson.melo
 */
public class UsuarioView extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */  
    
    Usuario user = new Usuario();
    
    public UsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_sobrenome = new javax.swing.JLabel();
        lbl_loguin = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        btn_CadastrarUsuario = new javax.swing.JButton();
        btn_LerUsuario = new javax.swing.JButton();
        tf_nome = new javax.swing.JTextField();
        tf_loguin = new javax.swing.JTextField();
        psf_senha = new javax.swing.JPasswordField();
        tf_sobrenome = new javax.swing.JTextField();
        btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_titulo.setText("Dados do Usuário");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_nome.setText("Nome:");

        lbl_sobrenome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_sobrenome.setText("Sobrenome:");

        lbl_loguin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_loguin.setText("Loguin:");

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_senha.setText("Senha:");

        btn_CadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CadastrarUsuario.setText("Cadastrar");
        btn_CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarUsuarioActionPerformed(evt);
            }
        });

        btn_LerUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_LerUsuario.setText("Ler");
        btn_LerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LerUsuarioActionPerformed(evt);
            }
        });

        btn_Limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_loguin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_loguin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_sobrenome)
                                .addComponent(lbl_nome)
                                .addComponent(lbl_senha))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nome)
                                .addComponent(psf_senha)
                                .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_CadastrarUsuario)
                            .addGap(18, 18, 18)
                            .addComponent(btn_LerUsuario)
                            .addGap(18, 18, 18)
                            .addComponent(btn_Limpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sobrenome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_loguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_loguin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(psf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CadastrarUsuario)
                    .addComponent(btn_LerUsuario)
                    .addComponent(btn_Limpar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarUsuarioActionPerformed
        
        String nome = tf_nome.getText();
        String sobrenome = tf_sobrenome.getText();        
        String loguin = tf_loguin.getText();
        char senha[] = psf_senha.getPassword();
      
        user.setNome(nome);
        user.setSobrenome(sobrenome);
        user.setLoguin(loguin);
        user.setSenha(senha);
                
        
    }//GEN-LAST:event_btn_CadastrarUsuarioActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        
        tf_nome.setText("");
        tf_sobrenome.setText("");        
        tf_loguin.setText("");
        psf_senha.setText("");
        
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_LerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LerUsuarioActionPerformed
        tf_nome.setText(user.getNome());
        tf_sobrenome.setText(user.getSobrenome());        
        tf_loguin.setText(user.getLoguin());
        psf_senha.setText(user.getSenha().toString());
    }//GEN-LAST:event_btn_LerUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CadastrarUsuario;
    private javax.swing.JButton btn_LerUsuario;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JLabel lbl_loguin;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_sobrenome;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPasswordField psf_senha;
    private javax.swing.JTextField tf_loguin;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_sobrenome;
    // End of variables declaration//GEN-END:variables
}
